version: "3.7"

# network to the mssql database
# setup the network before running the command
networks:
  db-net:
    external: true
  robotic-net:
    external: true

services:
  robotic-service:
    build:
      context: ../robotic-service
    image: robotic-portal/robotic-server:latest
    container_name: robotic-service
    hostname: robotic-portal
    # these pem file is mainly being used for encryption purpose
    # you may tweak the volumes by changing the path for the pem file
    volumes:
      - ../robotic-service/encryption-public-key.pem/:/usr/app/encryption-public-key.pem
      - ../robotic-service/encryption-private-key.pem/:/usr/app/encryption-private-key.pem
    env_file:
      - ../robotic-service/.env
      - .env
    networks:
      - db-net
      - robotic-net
    ports:
      - "8080:8080"

  robotic-admin-webapp:
    build:
      context: ../robotic-admin-webapp
      args:
        - DEPLOY_ENV=development
    image: robotic-portal/robotic-admin-webapp:latest
    container_name: robotic-admin-webapp
    hostname: robotic-admin-webapp
    networks:
      - robotic-net
    ports:
      - "3000:8080"

  robotic-student-webapp:
    build:
      context: ../robotic-student-webapp
      args:
        - DEPLOY_ENV=development
    image: robotic-portal/robotic-student-webapp:latest
    container_name: robotic-student-webapp
    hostname: robotic-student-webapp
    networks:
      - robotic-net
    ports:
      - "3004:8080"
