version: "3.7"

# network to the mssql database
# setup the network before running the command
networks:
  db-net:
    external: true

services:
  robotic-portal:
    build:
      context: ../Robotic Service
    image: robotic-portal/robotic-server:latest
    container_name: robotic-service
    hostname: robotic-portal
    # these pem file is mainly being used for encryption purpose
    # you may tweak the volumes by changing the path for the pem file
    volumes:
      - ../Robotic Service/encryption-public-key.pem/:/usr/app/encryption-public-key.pem
      - ../Robotic Service/encryption-private-key.pem/:/usr/app/encryption-private-key.pem
    env_file:
      - ../Robotic Service/.env
      - .env
    networks:
      - db-net
    ports:
      - "7000:8080"
    restart: on-failure
